### ISSUE TITLE
READMEに脱字があります

### ISSUE THREAD

**Issue by macocci7** [laravel-ja/ja-docs-11.x#1]
日本語訳の提供ありがとうございます。
翻訳の内容ではないのでプルリクエストではなく、ここに記載します。

▼脱字
- 1行目：
  - AS-IS「Laravel1.x公式ドキュメント翻訳リポジトリ」
  - TO-BE「Laravel11.x公式ドキュメント翻訳リポジトリ」
 
▼気になった箇所（バージョン数字の片方が全角）
- 82行目：
  - AS-IS「原則、Laravel1１.xのメンテ（バグフィックス）期間である１年６ヶ月間。」
  - TO-BE「原則、Laravel11.xのメンテ（バグフィックス）期間である１年６ヶ月間。」
 
▼他
- WEBサイトへのリンクをつけてはいかがでしょうか。
  （リポジトリ詳細のWebsiteかあるいはREADME内に）

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
