### ISSUE TITLE
Eloquent ORM の「APIリソース」がreadouble.comのメニューに表示されていない

### ISSUE THREAD

**Issue by yaegassy** [laravel-ja/ja-docs-11.x#7]
こんにちは。ドキュメントの更新、いつもありがとうございます。

一点、APIリソースがサイトのメニューに表示されていないようです。

<img width="1424" alt="laravel-ja-docs-issue" src="https://github.com/laravel-ja/ja-docs-11.x/assets/188642/e5109407-8e2c-4934-a773-ef46d9ee3e6a">

対象のmarkdownファイルやHTMLページ自体は存在するのは確認済みです。

- https://readouble.com/laravel/11.x/ja/eloquent-resources.html
- https://github.com/laravel-ja/ja-docs-11.x/blob/main/translation-ja/eloquent-resources.md

**Comment by HiroKws** [comment]
ありがとうございます。
APIドキュメントへのリンクを削除するコードでAPIで始まるURIのリンクも削除してしまっていました。修正しました。
同時に、eloquent関連のドキュメントを選択すると、ページ（章）選択パネルでeloquent関連リンク全部がdisableになるバグも修正いたしました。
ご報告、感謝いたします。
