### ISSUE TITLE
「全テーブル削除後マイグレーション」 内の脱字

### ISSUE THREAD

**Issue by gakisan8273** [laravel-ja/ja-docs-11.x#8]
ドキュメントの提供ありがとうございます。

`マイグレーション → 全テーブル削除後マイグレーション` 内に脱字を見つけました。

> デフォルトのデータベース接続からテーブルを削除するだけす。

と記載されてますが、 `テーブルを削除するだけです。` が正かなと思います。

<img width="797" alt="スクリーンショット 2024-08-05 23 33 40" src="https://github.com/user-attachments/assets/4936721a-5628-46b2-a666-ace6113f867d">

[該当箇所へのリンク](https://readouble.com/laravel/11.x/ja/migrations.html#column-method-foreignIdFor:~:text=%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%A7migrate%3Afresh%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%AF%E3%80%81%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E6%8E%A5%E7%B6%9A%E3%81%8B%E3%82%89%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B%E3%81%A0%E3%81%91%E3%81%99%E3%80%82%E3%81%97%E3%81%8B%E3%81%97%E3%80%81%2D%2Ddatabase%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8C%E3%81%B0%E3%80%81%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%83%88%E3%81%99%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E6%8E%A5%E7%B6%9A%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E6%8E%A5%E7%B6%9A%E5%90%8D%E3%81%AF%E3%80%81%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AEdatabase%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A7%E5%AE%9A%E7%BE%A9%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E6%8E%A5%E7%B6%9A%E3%81%A8%E5%AF%BE%E5%BF%9C%E3%81%95%E3%81%9B%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82)

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
